### ISSUE TITLE
要是能有Telegram for mac的那种简洁模式就好了

### ISSUE THREAD

**Issue by 68cs** [festoney8/LiteLoaderQQNT-Telegram-Theme#29]
![iShot_2024-04-27_17 33 59](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/25496213/6a4c6bf3-f16e-4297-973d-099d7ac05031)

**Comment by festoney8** [comment]
可以通过 QQ 的窄栏模式 + 新增 transitio 样式实现类似的效果

**操作步骤：**

1. 更新主题到最新版，并安装插件 https://github.com/PRO-2684/transitio

2. 启用 QQ 的窄栏模式（点右上角的按钮），如果页面出故障，就多点几次

3. 将下方代码保存为 `sidebar.css` 文件，在 transitio 插件中导入并启用，这些代码的功能是把侧栏挪到底部
```css
:root {
    /* 边栏高度 */
    --bottom-sidebar-height: 45px;
}

.container {
    flex-direction: column-reverse !important;

    .sidebar {
        height: auto !important;
        width: 100% !important;

        .sidebar__upper {
            padding-top: 0 !important;

            .sidebar__avatar {
                display: none !important;
            }
        }

        .nav,
        .sidebar-nav {
            flex-direction: row !important;

            .nav-item:not([aria-label="消息"], [aria-label="联系人"], [aria-label="空间"]) {
                display: none !important;
            }

            .nav-item {
                height: var(--bottom-sidebar-height) !important;
                flex-grow: 1 !important;
            }

            .nav-item {
                &[aria-label="联系人"] {
                    order: 1;
                }

                &[aria-label="消息"] {
                    order: 2;
                }

                &[aria-label="空间"] {
                    order: 3;
                }

            }
        }

        .sidebar-wrapper {
            flex-direction: row-reverse !important;
        }

        .sidebar__lower {
            .func-menu.sidebar__menu {
                display: flex !important;
                flex-direction: row !important;
                height: 100% !important;

                .sidebar-tooltips {
                    height: 100% !important;

                    .func-menu-more-component.func-menu__item {
                        height: 100% !important;
                        margin: 0 !important;
                        padding: 0 !important;
                        width: var(--bottom-sidebar-height) !important;
                    }
                }
            }

            .func-menu__item_wrap:not(:last-child) {
                display: none !important;
            }
        }

        &:hover .sidebar__lower .func-menu__item_wrap:last-child {
            display: unset !important;
        }

        &:not(:hover) .sidebar__lower .func-menu__item_wrap:last-child {
            display: none !important;
        }
    }
}
```

4. 边栏相关颜色在 TG 主题设置里调节

效果图
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/36254268/4ab85137-e02c-4ea9-880b-be42249c24c4)
