### ISSUE TITLE
请问主题的输入框的浮动问题怎么解决

### ISSUE THREAD

**Issue by ECHOWIKM** [festoney8/LiteLoaderQQNT-Telegram-Theme#31]
使用主题以后，其他的功能都收回了，然后我想用轻量工具箱里的本地表情功能，但是这个功能全都缩在里面，点开很麻烦，我记得之前是有可以全部展示的功能（印象里？）然后如果工具箱里打开移动功能位置
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/122116925/ae08083a-4ddc-4702-aba8-b8e70502d509)
会变的很奇怪
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/122116925/835ee3a5-fc97-4b3e-933b-0320a2922a38)
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/122116925/36765472-0416-498e-9e13-c1c642615d80)
鼠标移动到上面可以，这个怎么修改呀
![image](https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/assets/122116925/77ad438e-5473-471c-9065-6e97f160f273)

**Comment by festoney8** [comment]
可以尝试用 [transitio插件](https://github.com/PRO-2684/transitio) 新增样式解决

1. 关闭轻量工具箱的“移动功能位置”一项

2. 安装 transitio，将下列代码保存为 `emoji.css` 文件，在 transitio 中导入，并启用

```css
/* 展示本地表情按钮 */
#app .aio .group-panel .group-chat .chat-input-area .chat-func-bar:not(:hover) .func-bar:nth-child(2) {
    display: flex !important
}
```
