### ISSUE TITLE
输入框想恢复到默认的有什么办法吗

### ISSUE THREAD

**Issue by bingbaicai** [festoney8/LiteLoaderQQNT-Telegram-Theme#34]
输入框想恢复到默认的有什么办法吗？

**Comment by festoney8** [comment]
需要简单修改一下代码

1. 把这句代码注释掉
https://github.com/festoney8/LiteLoaderQQNT-Telegram-Theme/blob/c790d40074d2fbf25c74b20d79420c5527249e24/src/style/telegram.scss#L375

2. 用工具将 scss 文件重新转换成 css 文件，替代目录下的 telegram.css 文件。我使用的是 vscode 的 scss-to-css 插件

**Comment by bingbaicai** [comment]
感谢大佬！已经搞定

**Comment by festoney8** [comment]
看了一下，给输入框补一些基本样式会好看些，可以把注释的那一行周边的代码修改成如下

```scss
            & .group-chat {
                @include chat-msg-area();
                // @include chat-input-area();
                & .chat-input-area {
                    background-color: var(--tg-chat-input-area-bg-color) !important;
                    margin: 10px;
                    border-radius: 10px;
                }
            }
```

**Comment by bingbaicai** [comment]
> 看了一下，给输入框补一些基本样式会好看些，可以把注释的那一行周边的代码修改成如下
> 
> ```css-scss
>             & .group-chat {
>                 @include chat-msg-area();
>                 // @include chat-input-area();
>                 & .chat-input-area {
>                     background-color: var(--tg-chat-input-area-bg-color) !important;
>                     margin: 10px;
>                     border-radius: 10px;
>                 }
>             }
> ```

哈 我是准备回来找你呢，恢复的默认他输入框里面的字体非常小 在主题里面设置还不起作用，我试试你最新的

**Comment by festoney8** [comment]
最初的注释是把下方 `@mixin chat-input-area()` 中的大量代码都禁用了，字体调节不会生效

如果要保留住字号调节这些功能，需要从 TG 主题搬回来一些样式，试试下方代码

也可以在 LLQQNT 的 telegram 群内戳我，更方便些

```scss
            // 聊天栏
            & .group-chat {
                @include chat-msg-area();
                // @include chat-input-area();
                & .chat-input-area {
                    background-color: var(--tg-chat-input-area-bg-color) !important;
                    margin: 10px;
                    border-radius: 10px;
                    & .ck-content {
                        // 文字样式
                        font-size: var(--tg-chat-input-area-font-size) !important;
                        line-height: calc(var(--tg-chat-input-area-font-size) + 5px) !important;
                        color: var(--tg-chat-input-area-font-color) !important;

                        // 文字输入框 placeholder
                        & .ck-placeholder:before {
                            --qq-editor-placeholder: 'Write a message...';
                            color: var(--tg-chat-input-area-placeholder-font-color);
                        }

                        // 编辑器内at用户
                        & msg-at {
                            font-size: var(--tg-chat-input-area-font-size) !important;
                            line-height: calc(var(--tg-chat-input-area-font-size) + 5px) !important;
                        }
                    }
                }
            }
```
