### ISSUE TITLE
普通群成员的头衔消失、所有等级、自定义头衔消失

### ISSUE THREAD

**Issue by terminator7211** [festoney8/LiteLoaderQQNT-Telegram-Theme#47]
![QQ20240901-181145](https://github.com/user-attachments/assets/8a4b4c58-9e2d-42d8-ad0b-7a2e824563c4)
![63e35680-9919-4264-a6c0-feb99324bd84](https://github.com/user-attachments/assets/ee4ee7b4-68d3-42f1-aff7-63cf825b02c5)
如图，在开启了开启tg风格插件后，普通群成员的头衔消失了

**Comment by festoney8** [comment]
这是因为有壁纸背景时显示 tag 观感很差，所以主题默认只保留了群主和管理员这两个重要 tag

可以用 https://github.com/PRO-2684/transitio 插件强行让头衔和等级显示出来，自定义样式如下

 ```css
/* telegram-theme 显示群头衔 */
#app .message-container .user-name .q-tag {
    .level {
        display: initial !important
    }

    &.q-tag--grey,
    &.q-tag--purple {
        display: initial !important
    }
}
```
